### ISSUE TITLE
Hi;

### ISSUE THREAD

**Issue by korneelb** [OctoPrint/OctoPrint-SoftwareUpdate#1]
Hi;

i log in to my octopi installation, and run pip install https://github.com/OctoPrint/OctoPrint-SoftwareUpdate/archive/master.zip . at this point,e verything starts, but it lets met know that it can't find an Octoprint installation..

**Comment by foosel** [comment]
Since you are running OctoPi, you'll need to use ``~/oprint/bin/pip install ...``.

But please note: This plugin is not officially supported yet - which is why it lacks any documentation to begin with ;) I can't help you setting it up at this time, and you'll need to configure a bunch of things for it to work. Please wait a bit longer.

**Comment by foosel** [comment]
Also: "Hi;" is not a really descriptive title for a bug report...
